name: MaLootin
version: 1.0.7
main: com.maria.looting.Main
author: [Maria_BR]
commands:
  looting:
    aliases: [pilhagem]
  converterlooting:
    aliases: [lootingconvert, converterl, convertlooting, convertl, lconvert, trocarlooting]
  ma:
    aliases: [maria, mariadev, mariaplugins]